---
repo-name: peripherals-ldap
categories:
  - Identity Management
display-name: LDAP
manufacturer: N/A
product: N/A
description: The Lightweight Directory Access Protocol is an open, vendor-neutral, industry standard application protocol for accessing and maintaining distributed directory information services over an Internet Protocol network.
